Repository tkalejandro/portfolio-sonia-coronado, pull requests merged in 2023-10, with the labels that each got.

#13 6 install documantation library
  package-lock.json
  package.json
  src/app/docs/[...slug]/page.tsx
  src/app/docs/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/docs/about/index.md
  src/docs/about/purpose-behind-sonia-coronado-portfolio.md
  src/docs/environment/node.md
  src/docs/github/how-to-create-an-issue.md
  src/docs/github/how-to-start-a-new-branch.md
  src/docs/github/index.md
  src/docs/index.md
  src/docs/three/physics-rapier-methods.md
  src/modules/DocApp/DocApp.tsx
  src/modules/Portfolio/Portfolio.tsx
  src/styles/globals.css
  src/types/DocAppTypes/ContentSection.ts
  src/types/DocAppTypes/index.ts
Labels: documentation, feature

#19 Sonia resume was created as an object and ts typed.
  src/app/portfolio/page.tsx
  src/app/resume/page.tsx
  src/data/index.ts
  src/data/soniaCoronado.ts
  src/modules/Portfolio/Portfolio.tsx
  src/modules/Resume/Resume.tsx
  src/types/ResumeTypes/LifeHighlights.ts
  src/types/ResumeTypes/Resume.ts
  src/types/ResumeTypes/Skill.ts
  src/types/ResumeTypes/index.ts
Labels: issue

#22 Zustand added to project. Doc added.
  package-lock.json
  package.json
  src/docs/zustand/index.md
  src/modules/Resume/Resume.tsx
  src/store/index.ts
  src/store/useAppSettings.ts
  src/store/useDeveloperSettings.ts
Labels: feature

#28 Add guitar model and play button to welcome page
  src/modules/Experience/components/Welcome/Welcome.tsx
  src/styles/globals.css
Labels: Three
